### ISSUE TITLE
ontology visualization link in wiki is broken

### ISSUE THREAD

**Issue by andru1d** [ecologylab/BigSemantics#5]
clicking results in this:

HTTP ERROR: 404

Problem accessing /metametadata_ontology.html. Reason:

    Not Found

**Comment by quyin** [comment]
for any immediate use, the new URL is:
http://ecology-service.cse.tamu.edu/static/bsjs/mmdOntoVis/metametadata_ontology.html

it's not automatically updated through; the script for auto updating is
broken right now.

I'll come up with a better release process, and ask one of our REUs to
implement it.


--
Best Regards,
Yin Qu (屈垠)

**Comment by quyin** [comment]
the aforementioned URL is becoming the permanent URL for the ontology visualization. closing this.
